[project]
name = "asmodeus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Azrael", email = "azrael@mutualzz.com" }]
requires-python = ">=3.14"
dependencies = [
    "ddgs>=9.16.0",
    "faster-whisper>=1.2.1",
    "keyboard>=0.13.5",
    "numpy>=2.5.3",
    "ollama>=0.6.3",
    "openwakeword>=0.6",
    "piper-tts>=1.8.0",
    "sounddevice>=0.5.6",
]

[project.scripts]
asmodeus = "asmodeus:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
environments = ["sys_platform == 'win32'"]
